# Generated by Django 2.2.28 on 2023-08-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20230810_2024'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='package',
            name='services',
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='service.Service'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('listing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_listing', to='listing.Listing')),
                ('packages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_packages', to='service.Package')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='service.Service')),
            ],
        ),
    ]
