# Generated by Django 2.2.28 on 2023-08-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing'),
        ('users', '0002_auto_20230810_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_listings', to='listing.Listing'),
        ),
    ]
