# Generated by Django 2.2.28 on 2023-08-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='user_listings', to='listing.Listing'),
        ),
    ]
