# Generated by Django 2.2.28 on 2023-08-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20230810_2024'),
        ('service', '0002_auto_20230810_2024'),
        ('users', '0004_auto_20230810_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='service.Booking'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to='listing.Listing'),
        ),
    ]
